### ISSUE TITLE
Milestones for minimal complete DSL

### ISSUE THREAD

**Issue by zanellia** [zanellia/prometeo#1]
High-priority

- [] Support for basic types: int, double, bool, prmt_mat and prmt_vec
- [] Support for functions calls 
- [] Support for structures
- [] Support of arrays of all supported types
- [] Support for function definitions (no mem escape)
- [] Extend AST parser to keep track of heap usage

Low-priority

- [] Support for simple classes
